# Generated by Django 5.1.3 on 2025-03-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mortgage',
            table='mortgages',
        ),
    ]
